# Web Sunucu Portu
# encoding: UTF-8
server.port=8080

# H2 Dosya Tabanli Veritabani Ayarlari (MS SQL Modu)
spring.datasource.url=jdbc:h2:file:./ecotrace_data;MODE=MSSQLServer
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Web Konsolunu Aktifle?tir (SSMS Alternatifi)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate ve Veri Yükleme Ayarlari
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

